# Generated by Django 3.0.7 on 2020-07-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(default='Present', max_length=200),
        ),
    ]
