# Generated by Django 3.0.7 on 2020-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200716_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
