# Generated by Django 3.0.7 on 2020-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_education_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null='Not Applicable'),
        ),
    ]
