# Generated by Django 3.0.7 on 2020-07-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200716_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank='Not Applicable', max_length=200, null='Not Applicable'),
        ),
    ]
