# Generated by Django 3.0.7 on 2020-07-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200716_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(default='Not applicable', max_length=200),
        ),
    ]
